Dependency Manager improvements
joeyballentine/chaiNNer pull request #990
Opened 2022-09-18 18:38 UTC by joeyballentine

![image](https://user-images.githubusercontent.com/34788790/190923109-19c410fc-f3ce-4686-8a92-3890f272507d.png)

- Now says whether CUDA is supported or not rather than listing the first GPU
- Dependencies have dropdowns to show individual packages and the installed version
- Each dependency now has a hoverable description
- The console view has now been converted from an accordion to a toggle button

2022-09-20 13:34 UTC, RunDevelopment requested changes

2022-09-20 13:34 UTC, RunDevelopment commented on src/renderer/contexts/DependencyContext.tsx
> +                                }
I feel like it would be easier to just pass in `installedVersion: string | undefined` and then do these checks inside `IndividualDep`

2022-09-20 13:34 UTC, RunDevelopment commented
Sorry, I forgot to review this...

2022-09-20 13:44 UTC, joeyballentine commented on src/renderer/contexts/DependencyContext.tsx
> +                    {`${pkg.packageName} (${pkg.version || 'not installed'})`}
Oops

2022-09-21 12:42 UTC, RunDevelopment approved these changes

2022-09-21 13:20 UTC, merged